export const actionType = {

  PRODUCT_START_FETCHING: 'PRODUCT_START_FETCHING',
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_FETCH_ERROR: 'PRODUCT_FETCH_ERROR',

  A_PRODUCT_START_FETCHING: 'A_PRODUCT_START_FETCHING',
  A_PRODUCT_FETCHED: 'A_PRODUCT_FETCHED',
  A_PRODUCT_FETCH_ERROR: 'A_PRODUCT_FETCH_ERROR'


}