export const actionType = {

  PRODUCT_START_FETCHING: 'PRODUCT_START_FETCHING',
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_FETCH_ERROR: 'PRODUCT_FETCH_ERROR',

  A_PRODUCT_START_FETCHING: 'A_PRODUCT_START_FETCHING',
  A_PRODUCT_FETCHED: 'A_PRODUCT_FETCHED',
  A_PRODUCT_FETCH_ERROR: 'A_PRODUCT_FETCH_ERROR',

  ADDING_TO_CART: "ADDING_TO_CART",
  ADDED_TO_CART: "ADDED_TO_CART",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",

  // CART_UPDATING: 'CART_UPDATING',
  // CART_UPDATED: 'CART_UPDATED',
  // CART_UPDATE_ERROR: 'CART_UPDATE_ERROR',

  CHECKOUT_CREATING: 'CHECKOUT_CREATING',
  CHECKOUT_CREATED: 'CHECKOUT_CREATED',
  CHECKOUT_CREATE_ERROR: 'CHECKOUT_CREATE_ERROR',

  CHECKOUT_FETCHING: 'CHECKOUT_FETCHING',
  CHECKOUT_FETCHED: 'CHECKOUT_FETCHED',
  CHECKOUT_FETCH_ERROR: 'CHECKOUT_FETCH_ERROR',

}