export const actionType = {

  PRODUCT_START_FETCHING: 'PRODUCT_START_FETCHING',
  PRODUCT_FETCHED: 'PRODUCT_FETCHED',
  PRODUCT_FETCH_ERROR: 'PRODUCT_FETCH_ERROR',

  A_PRODUCT_START_FETCHING: 'A_PRODUCT_START_FETCHING',
  A_PRODUCT_FETCHED: 'A_PRODUCT_FETCHED',
  A_PRODUCT_FETCH_ERROR: 'A_PRODUCT_FETCH_ERROR',

  ADDING_TO_CART: "ADDING_TO_CART",
  ADDED_TO_CART: "ADDED_TO_CART",
  ADD_TO_CART_ERROR: "ADD_TO_CART_ERROR",

  CHECKOUT_ID_CREATING: 'CHECKOUT_ID_CREATING',
  CHECKOUT_ID_CREATED: 'CHECKOUT_ID_CREATED',
  CHECKOUT_ID_CREATE_ERROR: 'CHECKOUT_ID_CREATE_ERROR',


  



}